/*
 * Produktdaten.
 *
 * Jedes Produkt verlinkt entweder
 *   - auf eine konkrete Amazon-Produktseite (Feld "asin", z. B. "B0XXXXXXX"), oder
 *   - auf eine Amazon-Suche (Feld "query"), falls kein "asin" gesetzt ist.
 * Der Partner-Tag aus js/config.js wird in beiden Fällen automatisch angehängt.
 *
 * Neue Produkte einfach als weiteres Objekt in PRODUCTS ergänzen.
 */

window.CATEGORIES = [
  { id: "oele", name: "Bräunungsöle & Beschleuniger", icon: "🌴",
    text: "Öle, Sprays und Beschleuniger für eine intensivere Bräune an der Sonne." },
  { id: "selbstbraeuner", name: "Selbstbräuner", icon: "✨",
    text: "Bräune ohne UV-Strahlung – Mousse, Lotion, Tropfen und Sprays." },
  { id: "kleidung", name: "Durchbräunende Kleidung", icon: "👙",
    text: "Tan-Through-Bademode für eine Bräune ohne Streifen." },
  { id: "solarium", name: "Sonnenbänke & Heimsolarien", icon: "☀️",
    text: "Gesichtsbräuner, Heimsolarien und Ersatzröhren für zu Hause." },
  { id: "solariumkosmetik", name: "Solariumkosmetik", icon: "🧴",
    text: "Spezielle Lotionen für die Sonnenbank – ohne Öl, schonend für die Acrylscheiben." },
  { id: "sonnenschutz", name: "Sonnenschutz", icon: "🛡️",
    text: "Bräunen mit Köpfchen: Sonnencreme mit LSF für Körper, Gesicht und Lippen." },
  { id: "aftersun", name: "After-Sun & Pflege", icon: "💧",
    text: "Feuchtigkeit und Pflege, damit die Bräune länger hält." },
  { id: "zubehoer", name: "Zubehör", icon: "🧤",
    text: "Schutzbrillen, Applikationshandschuhe, Peelings und mehr." },
];

window.PRODUCTS = [
  // ---------- Bräunungsöle & Beschleuniger ----------
  { category: "oele", name: "Hawaiian Tropic Bräunungsöl", badge: "Klassiker",
    text: "Der Strand-Klassiker mit tropischem Duft – als Öl oder Spray, auch mit Lichtschutzfaktor erhältlich.",
    query: "Hawaiian Tropic Bräunungsöl" },
  { category: "oele", name: "Carroten Bräunungsöl",
    text: "Beliebtes Karotten-Bräunungsöl für einen goldenen Teint.",
    query: "Carroten Bräunungsöl" },
  { category: "oele", name: "Bräunungsbeschleuniger Lotion",
    text: "Beschleuniger zum Auftragen vor dem Sonnenbad – pflegt und unterstützt die natürliche Bräunung.",
    query: "Bräunungsbeschleuniger Lotion" },
  { category: "oele", name: "Trockenöl mit LSF",
    text: "Leichtes Trockenöl, das schnell einzieht, nicht klebt und die Haut glänzen lässt.",
    query: "Trockenöl Sonnenschutz LSF Bräune" },
  { category: "oele", name: "Kokosöl zum Bräunen",
    text: "Natürliches Kokosöl als Pflege-Basis – nur in Kombination mit Sonnenschutz verwenden.",
    query: "Kokosöl Bräunung Sonnenöl" },
  { category: "oele", name: "Beta-Carotin Kapseln",
    text: "Nahrungsergänzung mit Beta-Carotin – beliebt zur Vorbereitung der Haut auf den Sommer.",
    query: "Beta Carotin Kapseln Bräune" },

  // ---------- Selbstbräuner ----------
  { category: "selbstbraeuner", name: "Bondi Sands Selbstbräunungs-Schaum", badge: "Bestseller",
    text: "Leichter Schaum mit Kokos-Duft für eine gleichmäßige, natürliche Bräune.",
    query: "Bondi Sands Self Tanning Foam" },
  { category: "selbstbraeuner", name: "St. Tropez Self Tan",
    text: "Premium-Selbstbräuner mit Farbführung – so siehst du, wo du schon aufgetragen hast.",
    query: "St Tropez Self Tan Mousse" },
  { category: "selbstbraeuner", name: "Selbstbräunungstropfen fürs Gesicht",
    text: "Einfach ein paar Tropfen in die tägliche Gesichtscreme mischen – Bräune individuell dosierbar.",
    query: "Selbstbräuner Tropfen Gesicht" },
  { category: "selbstbraeuner", name: "Graduelle Bräunungslotion",
    text: "Tägliche Bodylotion mit leichtem Bräunungseffekt, der sich langsam aufbaut.",
    query: "graduelle Selbstbräunungslotion Körper" },
  { category: "selbstbraeuner", name: "Selbstbräuner Spray",
    text: "Sprühnebel für schwer erreichbare Stellen wie den Rücken.",
    query: "Selbstbräuner Spray Körper" },
  { category: "selbstbraeuner", name: "Selbstbräunungs-Tücher",
    text: "Praktisch für unterwegs und für Einsteiger – schnell und ohne Hilfsmittel.",
    query: "Selbstbräunungstücher" },

  // ---------- Durchbräunende Kleidung ----------
  { category: "kleidung", name: "Durchbräunender Bikini", badge: "Keine Streifen",
    text: "Tan-Through-Bikini aus speziellem Mikro-Lochgewebe – UV-Licht kommt durch, Streifen bleiben weg.",
    query: "durchbräunender Bikini" },
  { category: "kleidung", name: "Durchbräunender Badeanzug",
    text: "Einteiler aus durchbräunendem Material für eine gleichmäßige Bräune.",
    query: "durchbräunender Badeanzug Damen" },
  { category: "kleidung", name: "Durchbräunende Badehose Herren",
    text: "Badeshorts oder Slip aus Tan-Through-Stoff für Männer.",
    query: "durchbräunende Badehose Herren" },
  { category: "kleidung", name: "Durchbräunendes Top / Shirt",
    text: "Leichte Oberteile, die UV-Licht durchlassen – ideal für Garten und Balkon.",
    query: "durchbräunendes Shirt Tan Through" },
  { category: "kleidung", name: "Kiniki Tan-Through Bademode",
    text: "Bekannte Marke für durchbräunende Bademode in vielen Designs.",
    query: "Kiniki tan through" },

  // ---------- Sonnenbänke & Heimsolarien ----------
  { category: "solarium", name: "Gesichtsbräuner", badge: "Einsteiger",
    text: "Kompaktes Gerät für Gesicht, Hals und Dekolleté – passt auf jeden Tisch.",
    query: "Gesichtsbräuner" },
  { category: "solarium", name: "Heimsolarium",
    text: "Klappbares Ganzkörper-Solarium für zu Hause – vor dem Kauf Platzbedarf und Stromanschluss prüfen.",
    query: "Heimsolarium" },
  { category: "solarium", name: "Oberkörper-Bräuner (Deckenmodell)",
    text: "Solarium-Himmel zum Aufstellen oder Aufhängen, kombinierbar mit Liege.",
    query: "Solarium Himmel Oberkörperbräuner" },
  { category: "solarium", name: "Ersatzröhren für Solarien",
    text: "UV-Röhren zum Nachrüsten – auf die passende Länge und Wattzahl achten.",
    query: "Solarium Röhren Ersatz" },
  { category: "solarium", name: "Solarium-Timer / Zeitschaltuhr",
    text: "Für exakte Bräunungszeiten – wichtig für die Sicherheit.",
    query: "Zeitschaltuhr Solarium" },

  // ---------- Solariumkosmetik ----------
  { category: "solariumkosmetik", name: "Australian Gold Solariumlotion", badge: "Beliebt",
    text: "Bekannte Marke für Solariumkosmetik, verschiedene Intensitäten für jeden Hauttyp.",
    query: "Australian Gold Solarium Lotion" },
  { category: "solariumkosmetik", name: "Solarium Bräunungsbeschleuniger",
    text: "Intensivierende Lotion für die Sonnenbank – ohne Mineralöl, acrylschonend.",
    query: "Solarium Bräunungsbeschleuniger Lotion" },
  { category: "solariumkosmetik", name: "Solarium Bronzer",
    text: "Lotion mit Sofort-Bronzer für einen direkt sichtbaren Effekt.",
    query: "Solarium Lotion Bronzer" },
  { category: "solariumkosmetik", name: "Solarium Probierpackungen",
    text: "Sachets zum Testen verschiedener Lotionen – ideal zum Ausprobieren.",
    query: "Solarium Lotion Sachets Probe" },
  { category: "solariumkosmetik", name: "Tattoo-Schutz Stick",
    text: "Schützt Tattoos vor dem Ausbleichen unter UV-Licht.",
    query: "Tattoo Sonnenschutz Stick" },

  // ---------- Sonnenschutz ----------
  { category: "sonnenschutz", name: "Sonnenspray LSF 30",
    text: "Solider Allround-Schutz für Körper – leicht zu verteilen.",
    query: "Sonnenspray LSF 30" },
  { category: "sonnenschutz", name: "Sonnencreme Gesicht LSF 50",
    text: "Leichte Gesichtscreme mit hohem Schutz – das Gesicht altert am schnellsten durch UV.",
    query: "Sonnencreme Gesicht LSF 50" },
  { category: "sonnenschutz", name: "Lippenpflege mit LSF",
    text: "Lippen haben kaum Eigenschutz – ein Stick mit LSF gehört in jede Strandtasche.",
    query: "Lippenpflege LSF 30" },
  { category: "sonnenschutz", name: "Bräunungsfördernde Sonnenmilch",
    text: "Sonnenschutz mit bräunungsaktivierenden Wirkstoffen – schützt und unterstützt die Bräune.",
    query: "Sonnenmilch Bräunung aktivierend LSF" },

  // ---------- After-Sun & Pflege ----------
  { category: "aftersun", name: "After-Sun Lotion",
    text: "Kühlt und spendet Feuchtigkeit nach dem Sonnenbad – hilft, die Bräune zu erhalten.",
    query: "After Sun Lotion" },
  { category: "aftersun", name: "Aloe Vera Gel",
    text: "Kühlendes Gel für gestresste Haut nach Sonne oder Solarium.",
    query: "Aloe Vera Gel After Sun" },
  { category: "aftersun", name: "Bräunungsverlängernde Bodylotion",
    text: "After-Sun mit Tan-Extender-Effekt für länger anhaltende Bräune.",
    query: "After Sun Bräune verlängern Lotion" },
  { category: "aftersun", name: "Feuchtigkeitsspray",
    text: "Erfrischendes Spray für zwischendurch.",
    query: "After Sun Spray kühlend" },

  // ---------- Zubehör ----------
  { category: "zubehoer", name: "Solarium-Schutzbrille", badge: "Pflicht",
    text: "UV-Schutzbrille für die Sonnenbank – schützt die Augen zuverlässig.",
    query: "Solarium Schutzbrille UV" },
  { category: "zubehoer", name: "Selbstbräuner-Handschuh",
    text: "Applikationshandschuh für ein streifenfreies Ergebnis und saubere Hände.",
    query: "Selbstbräuner Handschuh" },
  { category: "zubehoer", name: "Rückenapplikator",
    text: "Damit kommst du ohne Hilfe an jede Stelle am Rücken.",
    query: "Rücken Applikator Selbstbräuner" },
  { category: "zubehoer", name: "Körperpeeling",
    text: "Vor dem Bräunen peelen sorgt für ein gleichmäßiges Ergebnis.",
    query: "Körperpeeling vor Selbstbräuner" },
  { category: "zubehoer", name: "Kabuki-Pinsel fürs Gesicht",
    text: "Zum gleichmäßigen Verblenden von Selbstbräuner im Gesicht.",
    query: "Kabuki Pinsel Selbstbräuner Gesicht" },
  { category: "zubehoer", name: "Strandliege / Sonnenliege",
    text: "Bequem bräunen – im Garten, auf dem Balkon oder am Pool.",
    query: "Sonnenliege klappbar" },
  { category: "zubehoer", name: "UV-Index Messgerät",
    text: "Zeigt die aktuelle UV-Stärke – hilft, die Zeit in der Sonne einzuschätzen.",
    query: "UV Index Messgerät" },
];
